### ISSUE TITLE
Getting an error as `column 'id' requires hydrate data from getKeyVaultSecret but none is available` on `azure_key_vault_secret` table

### ISSUE THREAD

**Issue by debabrat-git** [turbot/steampipe-plugin-azure#104]
**Describe the bug**

```
> select * from azure_key_vault_secret
Error: column 'id' requires hydrate data from getKeyVaultSecret but none is available

```

**Steampipe version (`steampipe -v`)**
 v0.4.1

**Plugin version (`steampipe plugin list`)**
Azure: v0.5.0

**To reproduce**
Don't enabled the secret and run the above query

**Comment by anisadas** [comment]
@debabrat-git This issue is resolved . One thing I like to add that is we are not allowed to perform get operation on disable secret so while doing this query `select * from azure_key_vault_secret`  on disable secret , some columns which has dependency on get function return null value .
Operation get is  allowed only on  enabled secret.
