### ISSUE TITLE
azure_mysql_server Does not show Flexible MySQL servers

### ISSUE THREAD

**Issue by fgomesz** [turbot/steampipe-plugin-azure#475]
[azure_mysql_server](https://hub.steampipe.io/plugins/turbot/azure/tables/azure_mysql_server) table does not show MySQL flexible servers https://docs.microsoft.com/en-us/azure/mysql/flexible-server/

It is not possible to assess all mysql servers if flexible servers are not shown.

**Comment by rajlearner17** [comment]
@fgomesz, Thanks for using Steampipe; I appreciate the continued feedback. 

`Flexible Server` was released on Nov 21 as GA. However, the GO SDK support was available since [May 21](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v58.0.0+incompatible/services/mysql/mgmt/2021-05-01/mysqlflexibleservers)

Steampipe `azure_mysql_server` was not supporting the` Flexible Server` and we used different [GO SDK](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v58.0.0+incompatible/services/mysql/mgmt/2020-01-01/mysql)

We understand that it's now incomplete without `Flexible Server`; we will look into it on priority.

**Comment by fgomesz** [comment]
Thank you for your support and I apologize for just asking for features and pointing things.

**Comment by rajlearner17** [comment]
@fgomesz No issue; it's great that you use and provide feedback to improve. We will get back on this. Thank you
