### ISSUE TITLE
Ignore Errors

### ISSUE THREAD

**Issue by ashitabh** [turbot/steampipe-plugin-azure#513]
Is it possible to ignore errors due to permission/access issues for a few Azure  resources
Here, we get access at RG level , but we can pass only subscription in config 
So basically I want to ignore access errors for other resources 
![image](https://user-images.githubusercontent.com/16971797/185917452-a2de1ae4-8553-4da9-be5d-4a8eeeff30f9.png)

**Comment by cbruno10** [comment]
@ashitabh Yes, it is possible, you can set the `ignore_error_codes` config argument per connection, which takes a list of error codes as strings, in order to avoid having Steampipe error when encountering those error codes:

For instance:
```
connection "azure" {
  plugin = "azure"

  # List of additional azure error codes to ignore for all queries.
  # By default, common not found error codes are ignored and will still be ignored even if this argument is not set.
  ignore_error_codes = ["NoAuthenticationInformation", "InvalidAuthenticationInfo", "AccountIsDisabled", "UnauthorizedOperation", "UnrecognizedClientException", "AuthorizationError", "AuthenticationFailed", "InsufficientAccountPermissions"]

  # Include other config args below
  ...
}
```

In the example above, you can also modify `ignore_error_codes` to just contain `AuthorizationFailed` based off of your screenshot.

For more information, please see [Azure Plugin Configuration](https://hub.steampipe.io/plugins/turbot/azure#configuration).

**Comment by ashitabh** [comment]
thanks a lot
