### ISSUE TITLE
Add table azure_private_dns_zone

### ISSUE THREAD

**Issue by Shr3ps** [turbot/steampipe-plugin-azure#582]
Related to #564

We also needs a table for Private DNS Zones (it's a different namespace)

SDK GO: https://github.com/Azure/azure-sdk-for-go/tree/v68.0.0/services/privatedns/mgmt

**Comment by pdecat** [comment]
I'll implement it too then :)

**Comment by cbruno10** [comment]
@Shr3ps Thanks for opening the issue!

@pdecat And thanks for taking on another table 😃. If you need any help, please let us know!

**Comment by pdecat** [comment]
On second thought, adding a new `azure_private_dns_zone` table renders the `zone_type` of the `azure_dns_zone` table kind of useless:

> `zone_type` | `text` | The type of this DNS zone (`Public` or `Private`).

Should I rather update the `azure_dns_zone` table hydrate functions to also query private DNS zones?

**Comment by pdecat** [comment]
On the other hand, it is actually a separate resource with the terraform provider: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_dns_zone

**Comment by cbruno10** [comment]
@pdecat Hm, that is strange that the Zone resource type has a `ZoneType` property. Is that property actually used by Azure for anything, considering they have 2 separate types for public vs. private zone? Maybe it was an older column they forgot about, as the private zone type doesn't have a `ZoneType` property.

Looking at the API, they do separate our [zone (public)](https://learn.microsoft.com/en-us/rest/api/dns/zones) vs. [private zone](https://learn.microsoft.com/en-us/rest/api/dns/privatedns/private-zones), though they both live under the `Microsoft.Network` provider based on the endpoint, e.g., `GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Network/privateDnsZones?$top={$top}&api-version=2018-09-01`.

When comparing the properties between the two types (https://learn.microsoft.com/en-us/rest/api/dns/privatedns/private-zones/list?tabs=HTTP#privatezone and https://learn.microsoft.com/en-us/rest/api/dns/zones/list?tabs=HTTP#zone), I do see different properties, so I think it would make senes to keep 2 separate tables since they'd have different table schemas.

**Comment by pdecat** [comment]
Agreed. I'm creating a new table, and updating examples of the other one.
