### ISSUE TITLE
Add table azurerm_web_pubsub

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-azure#628]
**References**
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/webpubsub/mgmt/2021-10-01/webpubsub

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/web_pubsub

Please add `privateEndpointConnections` details in the table.

Note: This table is required for NIST SP 800-53 Revision 5 compliance.

**Comment by ParthaI** [comment]
@khushboo9024, I have some findings regarding the availability of the API.

- The current version of the Azure GO SDK we are using is `v58.0.0+incompatible`. Unfortunately, there is no [API available](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v58.0.0+incompatible/services/web/mgmt/2021-02-01/web) in this version to retrieve PubSub details.
- However, in the [latest version of the SDK](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/webpubsub/mgmt/2021-10-01/webpubsub#Client.ListByResourceGroup) package, which is `v68.0.0+incompatible`, the API is available for retrieving PubSub details.
- In order to add this table, we need to update the SDK version to the latest one and then proceed with adding the table.

**Comment by misraved** [comment]
Thanks @ParthaI for adding the details 👍.

We are closing this issue since the SDK update is not on the immediate TODO list. We will reopen this issue once we attempt to update the Azure Go SDK to the latest version.
