### ISSUE TITLE
Add `resources` information in table `azure_maintenance_configuration`

### ISSUE THREAD

**Issue by marcbrlcln** [turbot/steampipe-plugin-azure#760]
**Describe the solution you'd like**
It would be great to have a column `resources` in table `azure_maintenance_configuration` to list the resources attached to a maintenance configuration.

**Comment by ParthaI** [comment]
Hello @marcbrlcln, just to let you know, I reviewed the maintenance configuration [API references](https://learn.microsoft.com/en-us/rest/api/maintenance/operation-groups?view=rest-maintenance-2023-09-01-preview) and could not locate a direct API that supplies information on the resources added to the maintenance configuration. Consequently, we are temporarily stalled on this issue. Please share any insights you might have.

Thank you!

**Comment by misraved** [comment]
@marcbrlcln we are closing this issue since the API does not support the `resources` field in the Azure maintenance configuration list and get APIs.

Once the API support is available, we will reopen the issue.

@ParthaI could you please raise an issue with the Azure SDK team to add this field to the API response?
