### ISSUE TITLE
Support to Entra ID to get Storage Account Properties

### ISSUE THREAD

**Issue by sergioaten** [turbot/steampipe-plugin-azure#788]
**Describe the bug**
When I try to fetch all the storage accounts using the command `./steampipe query "select * FROM azure_storage_account" --output line`, I get an error message indicating that key-based authentication is not permitted on this storage account.

**Steampipe version (`steampipe -v`)**
v0.23.2

**Plugin version (`steampipe plugin list`)**
v0.59.0

**To reproduce**
1. Create a storage account in Azure that **ONLY** uses Entra ID for authentication.
![image](https://github.com/turbot/steampipe-plugin-azure/assets/94703619/de14cef2-352e-49ed-a2c3-72672fa7d82b)
2. Run the command `./steampipe query "select * FROM azure_storage_account" --output line`
![image](https://github.com/turbot/steampipe-plugin-azure/assets/94703619/47e00277-96a6-4f8e-a1c3-ef9a22515290)

**Expected behavior**
I expected to get a list of all storage accounts without any error.

**Additional context**
The error message is: `Error: azure: accounts.Client#GetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="KeyBasedAuthenticationNotPermitted" Message="Key based authentication is not permitted on this storage account.\nRequestId:69914422-101e-0067-25b2-c563fa000000\nTime:2024-06-23T21:18:15.3109599Z" (SQLSTATE HV000)`. 
This issue seems to occur because I am using **ONLY** Entra ID authentication for this storage account.

**Comment by ParthaI** [comment]
Hello @sergioaten,

I looked into the issue and was able to replicate the problem on my end.

Here’s what I understand:
- According to the error message, we are encountering a forbidden error when querying this table.
- This error does not occur with list/get API calls but arises when attempting to retrieve the properties of the storage account using the `GetServiceProperties` API call.
- The error occurs because either the configuration for the storage account restricts access to property details or the caller lacks the necessary permissions to make this API call.
- Typically, we don’t handle forbidden errors within the plugin itself.
- If you want to avoid forbidden errors while querying the table, you can take the following steps:
  - Query only the columns that do not require extra hydrate calls to populate values, such as `select name, id, type, access_tier, kind, sku_name, creation_time from azure_storage_account`.
  - Configure the `ignore_error_codes` in your connection configuration file (`azure.spc`).

Example configuration:
```hcl
connection "azure" {
  plugin = "azure"
  // Other configurations

  ignore_error_codes = ["KeyBasedAuthenticationNotPermitted"]
}
```

Thanks!

**Comment by sergioaten** [comment]
As far as I can see it happens in any Storage Account, whether access is controlled by Login ID or Access Key.

I have enough permissions in all the storage account that I am testing, since it is my environment, if I make the calls directly by API, I can make them without problem, is it necessary to add some option to the authentication? I'm authenticated by AZ CLI with az login

Something happens because in each request, the error changes and even in some, it shows me some Storage Account.

So... why if I don't ignore this kind of errors?

Translated with DeepL.com (free version)

**Comment by ParthaI** [comment]
Hello @sergioaten,

When you run the query `select * from azure_storage_account`, the following API calls are made:

1. To list all storage accounts within a subscription:
   - API: [List API](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/storage/mgmt/2022-05-01/storage#AccountsClient.List)
   - Equivalent Azure CLI command: `az storage account list`

2. To get details of a specific storage account:
   - API: [GetProperties API](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/storage/mgmt/2022-05-01/storage#AccountsClient.GetProperties)
   - Equivalent Azure CLI command: `az storage account show --resource-group demo --name test732`

3. For Storage Account Lifecycle Management Policy:
   - API: [ManagementPoliciesClient.Get](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/storage/mgmt/2022-05-01/storage#ManagementPoliciesClient.Get)
   - Equivalent Azure CLI command: `az storage account management-policy show --account-name mystorageaccount --resource-group myresourcegroup`

4. To get Azure Storage Account Blob Properties:
   - API: [BlobServicesClient.GetServiceProperties](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v68.0.0+incompatible/services/storage/mgmt/2022-05-01/storage#BlobServicesClient.GetServiceProperties)
   - Equivalent Azure CLI command: `az storage account blob-service-properties show --account-name mystorageaccount --resource-group myresourcegroup`

5. For Azure Storage Account Table Properties:
   - API: [ServiceClient.GetProperties](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/data/aztables@v1.2.0#ServiceClient.GetProperties)

6. For Azure Storage Account Blob Service Logging:
   - API: [Client.GetServiceProperties](https://pkg.go.dev/github.com/tombuildsstuff/giovanni@v0.15.1/storage/2019-12-12/blob/accounts#Client.GetServiceProperties)

7. To get Azure Storage Account Queue Properties:
   - API: [Client.GetServiceProperties](https://pkg.go.dev/github.com/tombuildsstuff/giovanni@v0.15.1/storage/2018-11-09/queue/queues#Client.GetServiceProperties)

We are encountering a forbidden error for points 5, 6, and 7 when the `Allow storage account key access` is disabled, as the client is created using the storage account key. You can find more details [here](https://github.com/turbot/steampipe-plugin-azure/blob/main/azure/table_azure_storage_account.go#L655).

If we switch to using Entra ID for authentication, it may cause breaking changes due to different API packages. It's also unclear if we will need to authenticate using storage account keys in some cases.

I have pushed the changes to the branch `issue-788` and mapped the column values according to the API response. I believe there should be no discrepancies in the results between the current plugin version and the plugin built from this branch. Please try it out and share your feedback.

Thanks!

**Comment by ParthaI** [comment]
Hey @sergioaten, did you have a chance to review the conversation above?

**Comment by ParthaI** [comment]
Hello @sergioaten, we are closing this issue Since we haven’t heard back from you in some time, we’re assuming that the issue has been resolved or that it’s no longer a concern.

As a result, we will proceed with closing this issue. However, if you still require assistance or have any further questions, please don't hesitate to reach out. We would be happy to reopen the issue and assist you further.

Thank you!
